# Generated by Django 3.2 on 2021-05-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_ordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='email',
            new_name='phone',
        ),
    ]
