# Generated by Django 3.2 on 2021-05-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0007_auto_20210503_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='ordereditems',
            field=models.CharField(max_length=25),
        ),
    ]
