# Generated by Django 3.2 on 2021-05-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0011_alter_ordermodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
            preserve_default=False,
        ),
    ]
