# Generated by Django 4.2.1 on 2023-05-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitaldata.department'),
            preserve_default=False,
        ),
    ]
