# Generated by Django 4.2.1 on 2023-05-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitaldata', '0002_service_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='services',
        ),
    ]
